# Generated by Django 4.0.1 on 2022-01-19 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_user_userprofile_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='preferred_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
