# Generated by Django 4.0.1 on 2022-01-23 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_userprofile_preferred_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='avatar_url',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='codepen_username',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='current_level',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='discord_name',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='fcc_profile_url',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='github_username',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='name',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='preferred_name',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='timezone',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='age',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='contact_add',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='fname',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='gender',
            field=models.IntegerField(choices=[(0, 'Select Gender'), (1, 'Male'), (2, 'Female'), (3, 'Transgender')], default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='lname',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='mname',
            field=models.CharField(default='', max_length=100),
        ),
    ]
