# Generated by Django 4.0.1 on 2022-01-23 18:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_ID', models.CharField(max_length=4, validators=[django.core.validators.RegexValidator(message='Length has to be 4', regex='^.{4}$')])),
                ('course_name', models.IntegerField(choices=[(0, 'Select Course'), (1, 'B.Tech'), (2, 'M.Tech'), (3, 'MBA')], default=0)),
                ('course_desc', models.TextField(blank=True, default='')),
            ],
        ),
    ]
