# Generated by Django 4.0.1 on 2022-01-23 19:25

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subjects',
            fields=[
                ('sub_ID', models.CharField(max_length=4, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator(message='Length has to be 4', regex='^.{4}$')])),
                ('name', models.CharField(default='', max_length=100)),
                ('course_ID', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='utils.course')),
            ],
        ),
    ]
